# Generated by Django 3.1.7 on 2021-02-28 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreP', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreE', models.CharField(max_length=50)),
                ('Pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Paisesapp.paises')),
            ],
        ),
    ]
